# Generated by Django 3.0 on 2021-02-05 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_ghi_nhan', models.DateTimeField(blank=True, null=True)),
                ('user_ghi_nhan', models.TextField(blank=True, null=True)),
                ('mo_ta_log', models.TextField(blank=True, null=True)),
                ('moi_truong', models.CharField(blank=True, max_length=10, null=True)),
                ('vi_tri', models.TextField(blank=True, null=True)),
                ('loai_log', models.IntegerField(blank=True, null=True)),
                ('trang_thai_log', models.IntegerField(blank=True, null=True)),
                ('dev_thuc_hien', models.TextField(blank=True, null=True)),
                ('ngay_test_lai', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
