# Generated by Django 3.1.6 on 2021-02-24 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buglogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('ten_du_an', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='log',
            name='du_an',
            field=models.ForeignKey(default='TDCN', on_delete=django.db.models.deletion.CASCADE, to='buglogs.project'),
            preserve_default=False,
        ),
    ]
