# Generated by Django 3.1.6 on 2021-02-24 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buglogs', '0002_auto_20210224_1007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='du_an',
        ),
    ]
