# Generated by Django 3.1.6 on 2021-02-24 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buglogs', '0003_remove_log_du_an'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='du_an',
            field=models.ForeignKey(default='TDCN', on_delete=django.db.models.deletion.CASCADE, to='buglogs.project'),
        ),
    ]
